"""Detect new/changed files in 1-tham-chieu/ before regenerating a VB.

Use case: user nói "soạn lại VB này" sau khi quăng thêm file vào folder.
AI cần biết có file mới (cần đọc) hoặc file cũ thay đổi (cần đọc lại) trước
khi gen lại file kết quả.

Manifest stored at: <work-folder>/0-ky-thuat/file-manifest.yaml
Format:
    files:
      - name: "CV-2250.pdf"
        size: 6630720
        mtime: 1746389760  # epoch seconds
        last_read: "2026-05-09"  # AI đã đọc trong session đó
"""
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

import argparse
import os
import time
from pathlib import Path


def read_manifest(manifest_path: Path) -> dict:
    """Read manifest YAML (simple key:value, no PyYAML dependency)."""
    if not manifest_path.is_file():
        return {"files": []}
    files = []
    current = None
    for line in manifest_path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        if s.startswith("- name:"):
            if current:
                files.append(current)
            current = {"name": s.split(":", 1)[1].strip().strip('"')}
        elif current is not None and ":" in s:
            k, v = s.split(":", 1)
            k = k.strip()
            v = v.strip().strip('"')
            try:
                current[k] = int(v)
            except ValueError:
                current[k] = v
    if current:
        files.append(current)
    return {"files": files}


def write_manifest(manifest_path: Path, files: list[dict]):
    lines = ["# File manifest — auto-generated by regenerate_check.py",
             "# Tracks files in 1-tham-chieu/ to detect new/changed since last regenerate.",
             "files:"]
    for f in files:
        lines.append(f'  - name: "{f["name"]}"')
        lines.append(f'    size: {f["size"]}')
        lines.append(f'    mtime: {f["mtime"]}')
        if "last_read" in f:
            lines.append(f'    last_read: "{f["last_read"]}"')
    manifest_path.write_text("\n".join(lines), encoding="utf-8")


def scan_folder(folder: Path) -> list[dict]:
    """Scan a folder, return list of {name, size, mtime}."""
    out = []
    for f in folder.iterdir():
        if not f.is_file():
            continue
        if f.name.startswith("~$"):  # Word lock files
            continue
        st = f.stat()
        out.append({
            "name": f.name,
            "size": st.st_size,
            "mtime": int(st.st_mtime),
        })
    return sorted(out, key=lambda x: x["name"])


def diff_files(current: list[dict], previous: list[dict]) -> dict:
    """Return {new, changed, removed, unchanged}."""
    prev_by_name = {f["name"]: f for f in previous}
    new = []
    changed = []
    unchanged = []
    for f in current:
        if f["name"] not in prev_by_name:
            new.append(f)
        else:
            p = prev_by_name[f["name"]]
            if f["size"] != p.get("size") or f["mtime"] != p.get("mtime"):
                changed.append({**f, "previous_size": p.get("size"),
                               "previous_mtime": p.get("mtime")})
            else:
                unchanged.append(f)
    cur_names = {f["name"] for f in current}
    removed = [f for f in previous if f["name"] not in cur_names]
    return {"new": new, "changed": changed, "removed": removed, "unchanged": unchanged}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("work_folder", help="Path to <NNNN>-<...> work folder")
    ap.add_argument("--update", action="store_true",
                    help="Update manifest after reporting (mark all as 'last_read=today')")
    args = ap.parse_args()

    work = Path(args.work_folder).resolve()
    if not work.is_dir():
        print(f"ERROR: not a directory: {work}", file=sys.stderr)
        return 1

    tham_chieu = work / "1-tham-chieu"
    ky_thuat = work / "0-ky-thuat"
    manifest_path = ky_thuat / "file-manifest.yaml"

    if not tham_chieu.is_dir():
        print(f"ERROR: 1-tham-chieu/ not found in {work}", file=sys.stderr)
        return 1
    ky_thuat.mkdir(exist_ok=True)

    current = scan_folder(tham_chieu)
    prev_data = read_manifest(manifest_path)
    previous = prev_data.get("files", [])

    diff = diff_files(current, previous)

    print(f"=== Regenerate check: {work.name} ===")
    print(f"Current 1-tham-chieu/ has {len(current)} file(s)")
    print(f"Manifest had {len(previous)} file(s)")
    print()

    if not previous:
        print("⚠ No previous manifest — first run. All files are 'new':")
        for f in current:
            print(f"  + {f['name']} ({f['size']:,} bytes)")
    else:
        if diff["new"]:
            print(f"🆕 NEW files ({len(diff['new'])}):")
            for f in diff["new"]:
                print(f"  + {f['name']} ({f['size']:,} bytes)")
        if diff["changed"]:
            print(f"🔄 CHANGED files ({len(diff['changed'])}):")
            for f in diff["changed"]:
                print(f"  ~ {f['name']} (size {f.get('previous_size')} → {f['size']})")
        if diff["removed"]:
            print(f"🗑 REMOVED files ({len(diff['removed'])}):")
            for f in diff["removed"]:
                print(f"  - {f['name']}")
        if not (diff["new"] or diff["changed"] or diff["removed"]):
            print("✓ No changes since last regenerate.")
        print()
        if diff["unchanged"]:
            print(f"= Unchanged: {len(diff['unchanged'])} file(s)")

    if args.update:
        today = time.strftime("%Y-%m-%d")
        for f in current:
            f["last_read"] = today
        write_manifest(manifest_path, current)
        print(f"\n✓ Updated manifest: {manifest_path}")

    # Exit code: 0 = no action needed, 1 = changes detected (worth re-reading)
    return 1 if (diff["new"] or diff["changed"]) else 0


if __name__ == "__main__":
    sys.exit(main())
